[discord]
bot_token = ""
announcements_channel = "1387030524702232581" # bot user must be able to send messages in this channel

[twitter]
api_key = ""
api_key_secret = ""

[bluesky]
endpoint = "https://bsky.social"
username = "mcsrweekly.bsky.social"
password = "" # no clue why bsky doesn't have a proper oauth system

[mastodon]
instance = "https://mastodon.social"
client_key = ""
client_secret = ""
access_token = "" # required scopes: profile, write:statuses
